name: Ecolony
version: '${version}'
main: com.ecolony.ecolony.Main
api-version: 1.19
authors: [ RyanTheTechMan ]
commands:
  ecolony:
    description: "Main Command for Ecolony"
    usage: "/ecolony <command>"
    aliases: ["ecolony", "ec"]
    permission: ecolony.command
    permission-message: "You do not have permission to use this command!"